#!/bin/sh
# NOTE: Everything but the diff & diff-ar commands are tested.
# git-boost init
# git-boost clone <<library-name>>
# git-boost diff <<library-name>>
# git-boost diff-ar <<library-name>>
# git-boost update <<library-name>>
# git-boost start <<library-name>>

if [ "$#" = "0" -o "$1" = "help" ]; then
    echo "git-boost usage: git-boost <<operation>> <<library-name>> [other-args]"
    echo "operations:"
    echo "  init: init a modular, gitted boost (library name not necessary)"
    echo "  clone: checkout a library using git-svn"
    echo "  update: update a library. To update auxillary components supply '_' for the library name."
    echo "  start: start work on a ticket. Creates and checks out a new branch."
    echo "         Supply '_' for the library name to work on auxillary components."
    echo "  end: ends work on a ticket. Deletes branches without merging back to master."
    echo "       Supply '_' for the library name to work on auxillary components."
    echo "  diff: create a patch to stdout for the given library & its libs dir."
    echo "        To diff auxillary components supply '_' for the library name."
    echo "  diff-ar: create patches and archive them."
    exit
fi

operation=$1

get_non_modular_files () {
    curl "http://svn.boost.org/svn/boost/trunk/boost-build.jam" > boost-build.jam
    curl "http://svn.boost.org/svn/boost/trunk/Jamroot" > Jamroot
    curl "http://svn.boost.org/svn/boost/trunk/boostcpp.jam" > boostcpp.jam
    curl "http://svn.boost.org/svn/boost/trunk/bootstrap.sh" > bootstrap.sh
    curl "http://svn.boost.org/svn/boost/trunk/bootstrap.bat" > bootstrap.bat

    curl "http://svn.boost.org/svn/boost/trunk/boost/blank.hpp" > boost/blank.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/blank_fwd.hpp" > boost/blank_fwd.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/config.hpp" > boost/config.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/python.hpp" > boost/python.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/type.hpp" > boost/type.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/static_assert.hpp" > boost/static_assert.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/ref.hpp" > boost/ref.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/operators.hpp" > boost/operators.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/static_assert.hpp" > boost/static_assert.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/utility.hpp" > boost/utility.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/assert.hpp" > boost/assert.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/integer.hpp" > boost/integer.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/throw_exception.hpp" > boost/throw_exception.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/function_equal.hpp" > boost/function_equal.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/mem_fn.hpp" > boost/mem_fn.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/current_function.hpp" > boost/current_function.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/integer_fwd.hpp" > boost/integer_fwd.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/integer_traits.hpp" > boost/integer_traits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/limits.hpp" > boost/limits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/cstdint.hpp" > boost/cstdint.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/get_pointer.hpp" > boost/get_pointer.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/checked_delete.hpp" > boost/checked_delete.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/next_prior.hpp" > boost/next_prior.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/noncopyable.hpp" > boost/noncopyable.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/iterator.hpp" > boost/iterator.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/shared_ptr.hpp" > boost/shared_ptr.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/shared_array.hpp" > boost/shared_array.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/unordered_set.hpp" > boost/unordered_set.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/scoped_ptr.hpp" > boost/scoped_ptr.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/implicit_cast.hpp" > boost/implicit_cast.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/compressed_pair.hpp" > boost/compressed_pair.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/call_traits.hpp" > boost/call_traits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/aligned_storage.hpp" > boost/aligned_storage.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/swap.hpp" > boost/swap.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/bind.hpp" > boost/bind.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/lexical_cast.hpp" > boost/lexical_cast.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/type_traits.hpp" > boost/type_traits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/is_placeholder.hpp" > boost/is_placeholder.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/visit_each.hpp" > boost/visit_each.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/memory_order.hpp" > boost/memory_order.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/concept_check.hpp" > boost/concept_check.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/concept_archetype.hpp" > boost/concept_archetype.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/multi_index_container.hpp" > boost/multi_index_container.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/multi_index_container_fwd.hpp" > boost/multi_index_container_fwd.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/optional.hpp" > boost/optional.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/none.hpp" > boost/none.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/none_t.hpp" > boost/none_t.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/unordered_map.hpp" > boost/unordered_map.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/cast.hpp" > boost/cast.hpp

    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/indirect_traits.hpp" > boost/detail/indirect_traits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/templated_streams.hpp" > boost/detail/templated_streams.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/workaround.hpp" > boost/detail/workaround.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/is_xxx.hpp" > boost/detail/is_xxx.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/sp_typeinfo.hpp" > boost/detail/sp_typeinfo.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/no_exceptions_support.hpp" > boost/detail/no_exceptions_support.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/iterator.hpp" > boost/detail/iterator.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/compressed_pair.hpp" > boost/detail/compressed_pair.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/call_traits.hpp" > boost/detail/call_traits.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/lcast_precision.hpp" > boost/detail/lcast_precision.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/binary_search.hpp" > boost/detail/binary_search.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/allocator_utilities.hpp" > boost/detail/allocator_utilities.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/container_fwd.hpp" > boost/detail/container_fwd.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/reference_content.hpp" > boost/detail/reference_content.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/detail/select_type.hpp" > boost/detail/select_type.hpp
    
    curl "http://svn.boost.org/svn/boost/trunk/boost/pending/queue.hpp" > boost/pending/queue.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/pending/property.hpp" > boost/pending/property.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/pending/cstddef.hpp" > boost/pending/cstddef.hpp
    curl "http://svn.boost.org/svn/boost/trunk/boost/pending/container_traits.hpp" > boost/pending/container_traits.hpp

    curl "http://svn.boost.org/svn/boost/trunk/boost/pending/detail/property.hpp" > boost/pending/detail/property.hpp
}

if [ "$1" = "init" ]; then
    if [ -d "boost" -o -d "tools" ]; then
        echo "ERROR: 'boost' or 'tools' directory already exists. Remove them first."
        exit 1
    fi

    mkdir boost
    mkdir boost/detail
    mkdir boost/pending
    mkdir boost/pending/detail
    mkdir libs

    git svn clone --revision HEAD "http://svn.boost.org/svn/boost/trunk/tools"

    get_non_modular_files

    exit
fi

if [ "$#" -eq "1" ]; then
    echo "ERROR: the '$1' option requires a library name"
    exit 1
fi

libraryname=$2

README="To apply:
- Apply headers.patch to boost/$libraryname
- Apply libs.patch to libs/$libraryname

Summary of changes made to boost/$libraryname:
"

README_INBETWEEN="

Summary of changes made to libs/$libraryname:
"

TOOLSREADME="To apply:
- Apply tools.patch to ./tools directory.

Summary of changes made:
"

if [ "$operation" = "clone" ]; then
    if [ -d "$libraryname" ]; then
        echo "ERROR: folder for library already exists"
        exit 1
    fi

    mkdir $libraryname
    mkdir $libraryname/include
    mkdir $libraryname/include/boost
    mkdir $libraryname/include/boost/$libraryname
    mkdir $libraryname/libs

    echo "cloning $libraryname's headers"
    git svn clone --revision HEAD "http://svn.boost.org/svn/boost/trunk/boost/$libraryname" "$libraryname/include/boost/$libraryname"
    echo "cloning $libraryname's other files"
    git svn clone --revision HEAD "http://svn.boost.org/svn/boost/trunk/libs/$libraryname" "$libraryname/libs"

    ln -s ../$libraryname/include/boost/$libraryname boost/$libraryname
    ln -s ../$libraryname/libs libs/$libraryname
elif [ "$operation" = "update" ]; then
    if [ "$libraryname" = "_" ]; then
        echo "updating tools"
        cd tools
        git svn fetch
        cd ..

        get_non_modular_files
    else
        echo "updating $libraryname's headers"
        cd $libraryname/include/boost/$libraryname
        git svn fetch
        echo "updating $libraryname's other files"
        cd ../../../libs
        git svn fetch
        cd ..
    fi
elif [ "$operation" = "start" ]; then
    if [ "$libraryname" = "_" ]; then
        cd tools
        git checkout -b devel
        cd ..
    else
        cd $libraryname/include/boost/$libraryname
        git checkout -b devel
        cd ../../../libs
        git checkout -b devel
        cd ..
    fi
    echo "created branches"
elif [ "$operation" = "end" ]; then
    $ANSWER=""
    
    while [ "$ANSWER" != "y" -a "$ANSWER" != "n" ]
    do
        echo "Are you sure? This will permanently delete changes made. Enter 'y' or 'n'."
        read ANSWER
    done
    
    if [ "$ANSWER" = "n" ]; then
        echo "ABORTED"
        exit 1
    fi

    if [ "$libraryname" = "_" ]; then
        cd tools
        git reset --hard HEAD
        git checkout master
        git branch -d devel
        cd ..
    else
        cd $libraryname/include/boost/$libraryname
        git reset --hard HEAD
        git checkout master
        git branch -d devel
        cd ../../../libs
        git reset --hard HEAD
        git checkout master
        git branch -d devel
        cd ..
    fi
    
    echo "branches deleted"
elif [ "$operation" = "diff" -o "$operation" = "diff-ar" ]; then
    if [ "$libraryname" = "_" ]; then
        svn diff tools > tools.patch
        echo "$TOOLSREADME" > README_base
        cd tools
        git log "--pretty=oneline" master..devel | cat README_base - > README
        cd ..
    else
        svn diff $libraryname/include/boost/$libraryname > headers.patch
        svn diff $libraryname/libs > libs.patch

        echo "$README" > README_base
        echo "$README_INBETWEEN" > README_3
        cd $libraryname/include/boost/$libraryname
        git log "--pretty=oneline" master..devel | cat README_base - README_INBETWEEN > README_2
        cd ../../../libs
        git log "--pretty=oneline" master..devel | cat README_2 - > README
        cd ..
    fi

    rm "README_*"

    if [ "$operation" = "diff-ar" ]; then
        if [ "$libraryname" = "_" ]; then
            tar -cvjf patch.tar.bz2 tools.patch README
            rm tools.patch README
        else
            tar -cvjf patch.tar.bz2 headers.patch libs.patch README
            rm headers.patch libs.patch README
        fi
    fi
else
    echo "ERROR: unknown operation '$operation'"
    exit 1
fi

